### PR TITLE
Que 1.0.0.beta compatibility

### PR DESCRIPTION
**Pull request by hlascelles**
This PR is to provide running compatibility checks with the que master branch (currently beta, soon to be version 1.0).

So far, it looks extremely good. Almost all the changes are in the specs to handle symbols instead of strings, as the hashes are no longer of type `IndifferentAccess`. It's quite likely a lot of the specs would still pass against 0.10.

As and when new versions of que are released, I will update this PR.

### CODE REVIEW

**Comment by hlascelles** [comment]
As it stands, this branch is fully functional with que master.

**Comment by jpsilvashy** [comment]
I haven't had much success getting the migrations to run for scheduler, anything I should know regarding 1.0 compatability and running the migrations? I just get `nil` when I run: `Que::Scheduler::Migrations.migrate!(version: 4)`

I should see the new audit table and such, right?

**Comment by hlascelles** [comment]
I just rebased this branch from master, set up a local test application and ran the migrations and it worked fine. The scheduler appears is enqueueing properly. 

Yes, you should see the audit table and so on after running that migration.

Try the following to see if this branch works for you...

* In one terminal, run `docker run -p 5430:5432 postgres:9.5.0`
* In another terminal, checkout this branch and run `DB_PORT=5430 DB_PASSWORD='' bundle exec rake spec`

You should see all the specs run, including migrations tests. Does that work?

**Comment by jordoh** [comment]
Hi @hlascelles - should this PR still be open? It looks like it was inadvertently closed by an un-related dependency update (#80).

**Comment by hlascelles** [comment]
Huh. You are absolutely right. I don't know what caused that. Thanks!

**Comment by hlascelles** [comment]
I've figured it out. It is a bug in dependabot that is generating invalid links: https://github.com/dependabot/feedback/issues/562

**Comment by hlascelles** [comment]
3.2.7 released

**Pull request merged**
