### PR TITLE
Check for row count option using a String key

### LINKED ISSUE #235: KeyError: key not found: :retain_row_count
The `Que::Scheduler::Jobs::QueSchedulerAuditClearDownJob` tries to pull the row count from passed options with `:retain_row_count`, a Symbol: https://github.com/hlascelles/que-scheduler/blob/2f7f93c55cbbcd840a72e0e2547eb8c42f371f82/lib/que/scheduler/jobs/que_scheduler_audit_clear_down_job.rb#L31

I'm not sure if this is due to something ActiveJob is messing with (even though it seems this job is _not_ wrapped by ActiveJob's `JobWrapper`).

The example from the project README defines the schedule in the YAML file with a string key: https://github.com/hlascelles/que-scheduler/blob/2f7f93c55cbbcd840a72e0e2547eb8c42f371f82/README.md#L194-L197

At least in my project and configuration, defining this with a Symbol key specifically is forbidden by Psych:

```yml
Que::Scheduler::Jobs::QueSchedulerAuditClearDownJob:
  cron: "0 0 * * *"
  args:
    :retain_row_count: 129600
```

causes a `Psych::DisallowedClass: Tried to load unspecified class: Symbol`.

Perhaps I am missing something obvious here, but I think this clear job may have been written _assuming_ a hash with indifferent access or Hashie or something, but this assumption doesn't seem to hold true (at least in all circumstances).

Perhaps the job could be adjusted to check for both a Symbol and a String key, esp given #214 and #207

### PR DESCRIPTION
**Pull request by bjeanes**
Fixes #235

### CODE REVIEW

**Comment by hlascelles** [comment]
Thank you for this! Looks good - I will just try and replicate it in a test. Either way, I will get this in soon and cut a release.

**Comment by hlascelles** [comment]
My work on this has expanded slightly, as I definitely wanted to add the change with a test to capture why.

I have added a [full end to end integration test](https://github.com/hlascelles/que-scheduler/pull/237/files#diff-619c34c79bfeb632f523a7676c82c2748a2137a5733bc5a13a86819a0b117a1eR5), and it has yielded that this is a version issue.

The results from GitLab show that it works for Que 0.x: https://gitlab.com/hlascelles/que-scheduler/-/jobs/990978014#L3981
And fails for Que 1.x: https://gitlab.com/hlascelles/que-scheduler/-/jobs/990978014#L3991

Which is good! Now it is explained...

I will complete the "adding acceptance test" PR, then merge this in on top.

Thank you again for taking the time to report it!

**Comment by bjeanes** [comment]
That's weird... because we are on Que 0.x! 🤔

**Comment by hlascelles** [comment]
I was about to get very confused... But I think the test is just the inversion of what "I was looking for". 

I get the job to enqueue with a symbol: https://github.com/hlascelles/que-scheduler/pull/237/files#diff-619c34c79bfeb632f523a7676c82c2748a2137a5733bc5a13a86819a0b117a1eR51
Then check it came through with a string (ie not what the runtime code expects!): https://github.com/hlascelles/que-scheduler/pull/237/files#diff-619c34c79bfeb632f523a7676c82c2748a2137a5733bc5a13a86819a0b117a1eR86

So actually I would expect this to pass with 0.x and fail with 1.x. Which is what we see, and matches what you see. Phew.

**Comment by bjeanes** [comment]
Hahah phew indeed. That makes sense. Thanks for the diligence identifying the source of the issue 🙏🏻

**Comment by hlascelles** [comment]
Will merge this now and lay an integration spec and a unit spec PR on top of it.

**Comment by hlascelles** [comment]
Opened: https://github.com/hlascelles/que-scheduler/pull/243

**Comment by hlascelles** [comment]
Released 4.1.0. https://rubygems.org/gems/que-scheduler/versions/4.1.0

Thanks for your help! You have been namechecked: https://github.com/hlascelles/que-scheduler/blob/master/README.md#contributors

**Pull request merged**
