### PR TITLE
Widen que version requirement to allow v1.0.0.beta5

### PR DESCRIPTION
**Pull request by ajoneil**

### CODE REVIEW

**Comment by hlascelles** [comment]
Thanks for this! Will cut a gem after work today.

**Comment by paduszynski** [comment]
Thanks for it :)

**Comment by hlascelles** [comment]
Hmm... I have built a new version, but no matter what I do, rubygems prevents me from publishing it.

```
You have enabled multi-factor authentication. Please enter OTP code.
Code:   111111
Your OTP code is incorrect. Please check it and retry.
```

The codes are right, I can log into the UI with the same code at the same time. I have tried 6 times over several minutes. I am at a loss... I will keep trying.

**Comment by hlascelles** [comment]
Aha, it was my API key (which is now called legacy-api-key in rubygems). It looks like, for whatever reason, legacy keys don't support OTP.

**Comment by hlascelles** [comment]
Gem 4.2.0 published! https://rubygems.org/gems/que-scheduler/versions/4.2.0

**Comment by ajoneil** [comment]
Great, thank you for the quick turnaround :)

**Pull request merged**
